import type { Brand, Outlet, DrinkCategory, Town, MrtStation } from './types';

// ─────────────────────────────────────────
// Towns & MRT
// ─────────────────────────────────────────

export const TOWNS: Town[] = [
  { name: 'Orchard',     slug: 'orchard',     description: 'Singapore\'s premier shopping belt, home to flagship bubble tea chains and trendy cafés.' },
  { name: 'Bugis',       slug: 'bugis',        description: 'A vibrant mix of heritage streets and modern malls — perfect for an afternoon boba crawl.' },
  { name: 'Chinatown',   slug: 'chinatown',    description: 'Historic shophouses meet artisanal tea culture in this beloved cultural enclave.' },
  { name: 'Tampines',    slug: 'tampines',     description: 'East Singapore\'s go-to hub, packed with popular bubble tea outlets in Century Square and Tampines Mall.' },
  { name: 'Woodlands',   slug: 'woodlands',    description: 'North Singapore\'s largest new town with a growing boba scene centred around Causeway Point.' },
  { name: 'Jurong East', slug: 'jurong-east',  description: 'The western hub anchored by Westgate and JEM, hosting a dense cluster of top tea brands.' },
  { name: 'Bedok',       slug: 'bedok',        description: 'A beloved heartland town where long queues for quality boba are practically a rite of passage.' },
  { name: 'Punggol',     slug: 'punggol',      description: 'Singapore\'s youngest eco-town, with a fast-growing food & beverage landscape by Waterway Point.' },
  { name: 'Ang Mo Kio',  slug: 'ang-mo-kio',   description: 'A classic HDB heartland town with a loyal local boba crowd and family-friendly tea haunts.' },
  { name: 'Bishan',      slug: 'bishan',       description: 'A central, well-connected neighbourhood — Junction 8 is the social hub for tea lovers.' },
  { name: 'Clementi',    slug: 'clementi',     description: 'Home to NUS students and young families who keep the bubble tea queues lively all day long.' },
  { name: 'Serangoon',   slug: 'serangoon',    description: 'NEX mall and the nearby Chomp Chomp area make Serangoon a popular boba destination.' },
  { name: 'Toa Payoh',   slug: 'toa-payoh',    description: 'One of Singapore\'s oldest estates, with an eclectic old-meets-new tea café culture.' },
];

export const MRT_STATIONS: MrtStation[] = [
  { name: 'Orchard',        slug: 'orchard-mrt',        line: 'North-South' },
  { name: 'Bugis',          slug: 'bugis-mrt',           line: 'East-West / Downtown' },
  { name: 'Chinatown',      slug: 'chinatown-mrt',       line: 'Downtown / North-East' },
  { name: 'Tampines',       slug: 'tampines-mrt',        line: 'East-West' },
  { name: 'Woodlands',      slug: 'woodlands-mrt',       line: 'North-South' },
  { name: 'Jurong East',    slug: 'jurong-east-mrt',     line: 'East-West / North-South' },
  { name: 'Bedok',          slug: 'bedok-mrt',           line: 'East-West' },
  { name: 'Punggol',        slug: 'punggol-mrt',         line: 'North-East' },
  { name: 'Ang Mo Kio',     slug: 'ang-mo-kio-mrt',      line: 'North-South' },
  { name: 'Bishan',         slug: 'bishan-mrt',          line: 'North-South / Circle' },
  { name: 'Clementi',       slug: 'clementi-mrt',        line: 'East-West' },
  { name: 'Serangoon',      slug: 'serangoon-mrt',       line: 'North-East / Circle' },
  { name: 'Toa Payoh',      slug: 'toa-payoh-mrt',       line: 'North-South' },
  { name: 'Dhoby Ghaut',    slug: 'dhoby-ghaut-mrt',     line: 'North-South / North-East / Circle' },
  { name: 'Somerset',       slug: 'somerset-mrt',        line: 'North-South' },
  { name: 'City Hall',      slug: 'city-hall-mrt',       line: 'North-South / East-West' },
];

// ─────────────────────────────────────────
// Drink Categories
// ─────────────────────────────────────────

export const CATEGORIES: DrinkCategory[] = [
  {
    id: 'cat-1',
    name: 'Brown Sugar Milk Tea',
    slug: 'brown-sugar-milk-tea',
    description: 'Indulgent caramelised brown sugar syrup swirled through fresh milk and chewy tapioca pearls. Singapore\'s most iconic boba style.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    published: true,
  },
  {
    id: 'cat-2',
    name: 'Taro Milk Tea',
    slug: 'taro-milk-tea',
    description: 'Creamy purple taro blended into a silky milk tea — mildly sweet, distinctly earthy, impossibly pretty.',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop',
    published: true,
  },
  {
    id: 'cat-3',
    name: 'Matcha Series',
    slug: 'matcha-series',
    description: 'Stone-ground ceremonial matcha from Japan paired with fresh milk or oat milk for a refined, slightly bitter balance.',
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800&auto=format&fit=crop',
    published: true,
  },
  {
    id: 'cat-4',
    name: 'Fruit Tea',
    slug: 'fruit-tea',
    description: 'Light, refreshing teas loaded with fresh fruit chunks, bursting popping boba, and floral notes. Perfect for Singapore\'s tropical heat.',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&auto=format&fit=crop',
    published: true,
  },
  {
    id: 'cat-5',
    name: 'Classic Milk Tea',
    slug: 'classic-milk-tea',
    description: 'The timeless foundation — strong brewed black tea meets creamy milk for the original bubble tea experience.',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&auto=format&fit=crop',
    published: true,
  },
  {
    id: 'cat-6',
    name: 'Cheese Foam',
    slug: 'cheese-foam',
    description: 'Velvety, lightly salted cream cheese foam crowning cold teas — sip from the side for the full taste contrast.',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=800&auto=format&fit=crop',
    published: true,
  },
  {
    id: 'cat-7',
    name: 'Yakult Series',
    slug: 'yakult-series',
    description: 'Tangy, probiotic-rich Yakult blended with teas and flavoured pearls — Singapore\'s favourite nostalgic twist.',
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=800&auto=format&fit=crop',
    published: true,
  },
  {
    id: 'cat-8',
    name: 'Tiger Sugar Special',
    slug: 'tiger-sugar-special',
    description: 'The legendary brown sugar boba milk with its iconic tiger-stripe drizzle up the cup walls.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
    published: true,
  },
];

// ─────────────────────────────────────────
// Brands
// ─────────────────────────────────────────

export const BRANDS: Brand[] = [
  {
    id: 'brand-1',
    name: 'Tiger Sugar',
    slug: 'tiger-sugar',
    logo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop',
    description: 'The originator of the brown sugar boba milk with its instantly recognisable tiger-stripe cup. Taiwan-born, globally adored, and always worth the queue in Singapore.',
    websiteUrl: 'https://www.tigersugar.com',
    instagramUrl: 'https://www.instagram.com/tigersugar_official',
    featured: true,
    published: true,
  },
  {
    id: 'brand-2',
    name: 'Gong Cha',
    slug: 'gong-cha',
    logo: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&auto=format&fit=crop',
    description: 'A Taiwanese pioneer of customisable milk teas, Gong Cha has become one of Singapore\'s most-loved boba chains with hundreds of drink combinations.',
    websiteUrl: 'https://gongcha.com.sg',
    instagramUrl: 'https://www.instagram.com/gongchasingapore',
    featured: true,
    published: true,
  },
  {
    id: 'brand-3',
    name: 'KOI Thé',
    slug: 'koi-the',
    logo: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&auto=format&fit=crop',
    description: 'Singapore\'s homegrown success story — founded locally and celebrated for its refined tea craftsmanship and signature fresh milk teas.',
    websiteUrl: 'https://www.koithe.com',
    instagramUrl: 'https://www.instagram.com/koithesg',
    featured: true,
    published: true,
  },
  {
    id: 'brand-4',
    name: 'LiHo Tea',
    slug: 'liho-tea',
    logo: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&auto=format&fit=crop',
    description: 'A proudly Singaporean brand born from a local partnership with Gong Cha. LiHo Tea balances classic Taiwanese flavours with Singapore-exclusive creations.',
    websiteUrl: 'https://www.lihosg.com',
    instagramUrl: 'https://www.instagram.com/lihosg',
    featured: true,
    published: true,
  },
  {
    id: 'brand-5',
    name: 'Chicha San Chen',
    slug: 'chicha-san-chen',
    logo: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&auto=format&fit=crop',
    description: 'A minimalist Taiwanese brand centred on premium loose-leaf teas, subtle sweetness, and zen-like presentation. A more sophisticated choice for the discerning tea lover.',
    websiteUrl: 'https://www.chicha.com.tw',
    instagramUrl: 'https://www.instagram.com/chicha.sg',
    featured: true,
    published: true,
  },
  {
    id: 'brand-6',
    name: 'Yi Fang Taiwan Fruit Tea',
    slug: 'yi-fang',
    logo: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=400&auto=format&fit=crop',
    description: 'Specialising in vibrant fruit teas made with real seasonal fruits, Yi Fang brings Taiwanese orchard freshness to the Singapore heat.',
    websiteUrl: 'https://yifang.com.sg',
    instagramUrl: 'https://www.instagram.com/yifangsg',
    featured: false,
    published: true,
  },
  {
    id: 'brand-7',
    name: 'R&B Tea',
    slug: 'rb-tea',
    logo: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&auto=format&fit=crop',
    description: 'Rhythm & Boba — R&B Tea brings together music-inspired branding and addictive brown sugar and cheese foam drinks in a cool, youthful setting.',
    websiteUrl: 'https://rbtea.sg',
    instagramUrl: 'https://www.instagram.com/rbteasg',
    featured: false,
    published: true,
  },
  {
    id: 'brand-8',
    name: 'Sunright Tea Studio',
    slug: 'sunright-tea-studio',
    logo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop',
    description: 'Sunright is the modern, artisanal face of Singapore\'s local tea scene — handcrafted drinks, natural ingredients, and beautifully designed cups.',
    websiteUrl: 'https://sunright.com.sg',
    instagramUrl: 'https://www.instagram.com/sunrightsg',
    featured: false,
    published: true,
  },
  {
    id: 'brand-9',
    name: 'Machi Machi',
    slug: 'machi-machi',
    logo: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&auto=format&fit=crop',
    description: 'Famous for its impossibly thick cheese foam and its signature scones, Machi Machi is a premium Taiwanese import that took Singapore by storm.',
    websiteUrl: 'https://machimachi.sg',
    instagramUrl: 'https://www.instagram.com/machimachi.sg',
    featured: false,
    published: true,
  },
  {
    id: 'brand-10',
    name: 'The Whale Tea',
    slug: 'the-whale-tea',
    logo: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&auto=format&fit=crop',
    description: 'With its charming whale mascot and playful branding, The Whale Tea serves up creative milk teas and yakult-based drinks that are as fun to look at as they are to drink.',
    websiteUrl: 'https://thewhaletea.com.sg',
    instagramUrl: 'https://www.instagram.com/thewhaleteasg',
    featured: false,
    published: true,
  },
];

// ─────────────────────────────────────────
// Outlets
// ─────────────────────────────────────────

export const OUTLETS: Outlet[] = [
  // Tiger Sugar
  {
    id: 'outlet-1',
    name: 'Tiger Sugar Orchard',
    slug: 'tiger-sugar-orchard',
    brandId: 'brand-1',
    brandName: 'Tiger Sugar',
    brandSlug: 'tiger-sugar',
    brandLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop',
    town: 'Orchard',
    townSlug: 'orchard',
    mall: 'ION Orchard',
    address: '2 Orchard Turn, #B4-49, ION Orchard, Singapore 238801',
    nearestMrt: 'Orchard',
    mrtSlug: 'orchard-mrt',
    openingHours: 'Mon–Thu 10am–10pm · Fri–Sun 10am–11pm',
    phone: '+65 6509 8888',
    googleMapsUrl: 'https://maps.google.com/?q=ION+Orchard+Singapore',
    deliveryLinks: [
      { platform: 'GrabFood', url: 'https://grab.com' },
      { platform: 'foodpanda', url: 'https://foodpanda.sg' },
    ],
    popularDrinks: ['Brown Sugar Boba Milk', 'Tiger Sugar Milk Tea', 'Matcha Latte with Boba'],
    drinkCategories: ['Brown Sugar Milk Tea', 'Tiger Sugar Special'],
    drinkCategorySlugs: ['brown-sugar-milk-tea', 'tiger-sugar-special'],
    priceRange: '$$',
    halalFriendly: false,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop',
    galleryImages: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&auto=format&fit=crop',
    ],
    featured: true,
    published: true,
  },
  {
    id: 'outlet-2',
    name: 'Tiger Sugar Tampines',
    slug: 'tiger-sugar-tampines',
    brandId: 'brand-1',
    brandName: 'Tiger Sugar',
    brandSlug: 'tiger-sugar',
    brandLogo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop',
    town: 'Tampines',
    townSlug: 'tampines',
    mall: 'Tampines Mall',
    address: '4 Tampines Central 5, #B1-34, Tampines Mall, Singapore 529510',
    nearestMrt: 'Tampines',
    mrtSlug: 'tampines-mrt',
    openingHours: 'Daily 10am–10pm',
    googleMapsUrl: 'https://maps.google.com/?q=Tampines+Mall+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Brown Sugar Boba Milk', 'Tiger Sugar Milk Tea'],
    drinkCategories: ['Brown Sugar Milk Tea', 'Tiger Sugar Special'],
    drinkCategorySlugs: ['brown-sugar-milk-tea', 'tiger-sugar-special'],
    priceRange: '$$',
    halalFriendly: false,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // Gong Cha
  {
    id: 'outlet-3',
    name: 'Gong Cha Bugis Junction',
    slug: 'gong-cha-bugis-junction',
    brandId: 'brand-2',
    brandName: 'Gong Cha',
    brandSlug: 'gong-cha',
    town: 'Bugis',
    townSlug: 'bugis',
    mall: 'Bugis Junction',
    address: '200 Victoria Street, #01-47, Bugis Junction, Singapore 188021',
    nearestMrt: 'Bugis',
    mrtSlug: 'bugis-mrt',
    openingHours: 'Daily 10am–10pm',
    phone: '+65 6338 9966',
    googleMapsUrl: 'https://maps.google.com/?q=Bugis+Junction+Singapore',
    deliveryLinks: [
      { platform: 'GrabFood', url: 'https://grab.com' },
      { platform: 'foodpanda', url: 'https://foodpanda.sg' },
    ],
    popularDrinks: ['Pearl Milk Tea', 'Earl Grey Milk Tea', 'Yakult Green Tea', 'Roasted Milk Tea'],
    drinkCategories: ['Classic Milk Tea', 'Yakult Series', 'Cheese Foam'],
    drinkCategorySlugs: ['classic-milk-tea', 'yakult-series', 'cheese-foam'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=1200&auto=format&fit=crop',
    featured: true,
    published: true,
  },
  {
    id: 'outlet-4',
    name: 'Gong Cha Jurong East',
    slug: 'gong-cha-jurong-east',
    brandId: 'brand-2',
    brandName: 'Gong Cha',
    brandSlug: 'gong-cha',
    town: 'Jurong East',
    townSlug: 'jurong-east',
    mall: 'JEM',
    address: '50 Jurong Gateway Rd, #B1-09, JEM, Singapore 608549',
    nearestMrt: 'Jurong East',
    mrtSlug: 'jurong-east-mrt',
    openingHours: 'Daily 10am–10pm',
    googleMapsUrl: 'https://maps.google.com/?q=JEM+Jurong+East+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Pearl Milk Tea', 'Yakult Green Tea', 'Cheese Milk Tea'],
    drinkCategories: ['Classic Milk Tea', 'Yakult Series'],
    drinkCategorySlugs: ['classic-milk-tea', 'yakult-series'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // KOI Thé
  {
    id: 'outlet-5',
    name: 'KOI Thé Orchard',
    slug: 'koi-the-orchard',
    brandId: 'brand-3',
    brandName: 'KOI Thé',
    brandSlug: 'koi-the',
    town: 'Orchard',
    townSlug: 'orchard',
    mall: '313@Somerset',
    address: '313 Orchard Road, #B2-36/37, 313@Somerset, Singapore 238895',
    nearestMrt: 'Somerset',
    mrtSlug: 'somerset-mrt',
    openingHours: 'Daily 10am–10pm',
    phone: '+65 6235 9778',
    googleMapsUrl: 'https://maps.google.com/?q=313+Somerset+Singapore',
    deliveryLinks: [
      { platform: 'GrabFood', url: 'https://grab.com' },
      { platform: 'foodpanda', url: 'https://foodpanda.sg' },
    ],
    popularDrinks: ['Fresh Milk Tea', 'Uji Matcha Latte', 'Golden Bubble Tea', 'KOI Signature'],
    drinkCategories: ['Classic Milk Tea', 'Matcha Series'],
    drinkCategorySlugs: ['classic-milk-tea', 'matcha-series'],
    priceRange: '$$',
    halalFriendly: false,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=1200&auto=format&fit=crop',
    featured: true,
    published: true,
  },
  {
    id: 'outlet-6',
    name: 'KOI Thé Bedok',
    slug: 'koi-the-bedok',
    brandId: 'brand-3',
    brandName: 'KOI Thé',
    brandSlug: 'koi-the',
    town: 'Bedok',
    townSlug: 'bedok',
    mall: 'Bedok Mall',
    address: '311 New Upper Changi Rd, #01-37, Bedok Mall, Singapore 467360',
    nearestMrt: 'Bedok',
    mrtSlug: 'bedok-mrt',
    openingHours: 'Daily 10am–10pm',
    googleMapsUrl: 'https://maps.google.com/?q=Bedok+Mall+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Fresh Milk Tea', 'Golden Bubble Tea'],
    drinkCategories: ['Classic Milk Tea'],
    drinkCategorySlugs: ['classic-milk-tea'],
    priceRange: '$$',
    halalFriendly: false,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // LiHo Tea
  {
    id: 'outlet-7',
    name: 'LiHo Tea Bishan',
    slug: 'liho-tea-bishan',
    brandId: 'brand-4',
    brandName: 'LiHo Tea',
    brandSlug: 'liho-tea',
    town: 'Bishan',
    townSlug: 'bishan',
    mall: 'Junction 8',
    address: '9 Bishan Place, #01-12, Junction 8, Singapore 579837',
    nearestMrt: 'Bishan',
    mrtSlug: 'bishan-mrt',
    openingHours: 'Mon–Thu 10am–10pm · Fri–Sun 10am–10:30pm',
    phone: '+65 6253 5858',
    googleMapsUrl: 'https://maps.google.com/?q=Junction+8+Bishan+Singapore',
    deliveryLinks: [
      { platform: 'GrabFood', url: 'https://grab.com' },
      { platform: 'foodpanda', url: 'https://foodpanda.sg' },
    ],
    popularDrinks: ['Brown Sugar Boba Latte', 'Cheese Matcha', 'LiHo Milk Tea', 'Strawberry Yakult'],
    drinkCategories: ['Brown Sugar Milk Tea', 'Cheese Foam', 'Yakult Series'],
    drinkCategorySlugs: ['brown-sugar-milk-tea', 'cheese-foam', 'yakult-series'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=1200&auto=format&fit=crop',
    featured: true,
    published: true,
  },
  {
    id: 'outlet-8',
    name: 'LiHo Tea Woodlands',
    slug: 'liho-tea-woodlands',
    brandId: 'brand-4',
    brandName: 'LiHo Tea',
    brandSlug: 'liho-tea',
    town: 'Woodlands',
    townSlug: 'woodlands',
    mall: 'Causeway Point',
    address: '1 Woodlands Square, #B1-28, Causeway Point, Singapore 738099',
    nearestMrt: 'Woodlands',
    mrtSlug: 'woodlands-mrt',
    openingHours: 'Daily 10am–10pm',
    googleMapsUrl: 'https://maps.google.com/?q=Causeway+Point+Woodlands+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['LiHo Milk Tea', 'Brown Sugar Boba Latte', 'Cheese Green Tea'],
    drinkCategories: ['Classic Milk Tea', 'Brown Sugar Milk Tea', 'Cheese Foam'],
    drinkCategorySlugs: ['classic-milk-tea', 'brown-sugar-milk-tea', 'cheese-foam'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // Chicha San Chen
  {
    id: 'outlet-9',
    name: 'Chicha San Chen Chinatown',
    slug: 'chicha-san-chen-chinatown',
    brandId: 'brand-5',
    brandName: 'Chicha San Chen',
    brandSlug: 'chicha-san-chen',
    town: 'Chinatown',
    townSlug: 'chinatown',
    mall: 'Chinatown Point',
    address: '133 New Bridge Rd, #02-28, Chinatown Point, Singapore 059413',
    nearestMrt: 'Chinatown',
    mrtSlug: 'chinatown-mrt',
    openingHours: 'Daily 11am–9pm',
    phone: '+65 6535 3638',
    googleMapsUrl: 'https://maps.google.com/?q=Chinatown+Point+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Roasted Milk Tea', 'Oolong Milk Tea', 'Assam Milk Tea', 'Honey Osmanthus Milk Tea'],
    drinkCategories: ['Classic Milk Tea'],
    drinkCategorySlugs: ['classic-milk-tea'],
    priceRange: '$$',
    halalFriendly: true,
    seatingAvailable: true,
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=1200&auto=format&fit=crop',
    featured: true,
    published: true,
  },

  // Yi Fang
  {
    id: 'outlet-10',
    name: 'Yi Fang Ang Mo Kio',
    slug: 'yi-fang-ang-mo-kio',
    brandId: 'brand-6',
    brandName: 'Yi Fang Taiwan Fruit Tea',
    brandSlug: 'yi-fang',
    town: 'Ang Mo Kio',
    townSlug: 'ang-mo-kio',
    mall: 'AMK Hub',
    address: '53 Ang Mo Kio Ave 3, #B1-62, AMK Hub, Singapore 569933',
    nearestMrt: 'Ang Mo Kio',
    mrtSlug: 'ang-mo-kio-mrt',
    openingHours: 'Daily 10am–10pm',
    googleMapsUrl: 'https://maps.google.com/?q=AMK+Hub+Ang+Mo+Kio+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Pineapple Green Tea', 'Strawberry Yakult', 'Passionfruit Tea', 'Lychee Fruit Tea'],
    drinkCategories: ['Fruit Tea', 'Yakult Series'],
    drinkCategorySlugs: ['fruit-tea', 'yakult-series'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // R&B Tea
  {
    id: 'outlet-11',
    name: 'R&B Tea Serangoon',
    slug: 'rb-tea-serangoon',
    brandId: 'brand-7',
    brandName: 'R&B Tea',
    brandSlug: 'rb-tea',
    town: 'Serangoon',
    townSlug: 'serangoon',
    mall: 'NEX',
    address: '23 Serangoon Central, #B1-45, NEX, Singapore 556083',
    nearestMrt: 'Serangoon',
    mrtSlug: 'serangoon-mrt',
    openingHours: 'Daily 10am–10pm',
    googleMapsUrl: 'https://maps.google.com/?q=NEX+Mall+Serangoon+Singapore',
    deliveryLinks: [
      { platform: 'GrabFood', url: 'https://grab.com' },
      { platform: 'foodpanda', url: 'https://foodpanda.sg' },
    ],
    popularDrinks: ['Brown Sugar Latte', 'Cheese Oolong', 'Panda Boba Milk Tea'],
    drinkCategories: ['Brown Sugar Milk Tea', 'Cheese Foam'],
    drinkCategorySlugs: ['brown-sugar-milk-tea', 'cheese-foam'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // Sunright Tea Studio
  {
    id: 'outlet-12',
    name: 'Sunright Tea Studio Clementi',
    slug: 'sunright-tea-studio-clementi',
    brandId: 'brand-8',
    brandName: 'Sunright Tea Studio',
    brandSlug: 'sunright-tea-studio',
    town: 'Clementi',
    townSlug: 'clementi',
    mall: 'Clementi Mall',
    address: '3155 Commonwealth Ave W, #B1-45, The Clementi Mall, Singapore 129588',
    nearestMrt: 'Clementi',
    mrtSlug: 'clementi-mrt',
    openingHours: 'Daily 10am–9:30pm',
    googleMapsUrl: 'https://maps.google.com/?q=The+Clementi+Mall+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Handcrafted Oolong', 'Taro Milk Tea', 'Matcha Latte'],
    drinkCategories: ['Taro Milk Tea', 'Matcha Series', 'Classic Milk Tea'],
    drinkCategorySlugs: ['taro-milk-tea', 'matcha-series', 'classic-milk-tea'],
    priceRange: '$$',
    halalFriendly: false,
    seatingAvailable: true,
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // Machi Machi
  {
    id: 'outlet-13',
    name: 'Machi Machi Orchard',
    slug: 'machi-machi-orchard',
    brandId: 'brand-9',
    brandName: 'Machi Machi',
    brandSlug: 'machi-machi',
    town: 'Orchard',
    townSlug: 'orchard',
    mall: 'Plaza Singapura',
    address: '68 Orchard Rd, #B2-22, Plaza Singapura, Singapore 238839',
    nearestMrt: 'Dhoby Ghaut',
    mrtSlug: 'dhoby-ghaut-mrt',
    openingHours: 'Daily 11am–9:30pm',
    phone: '+65 6337 7878',
    googleMapsUrl: 'https://maps.google.com/?q=Plaza+Singapura+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Brown Sugar Milk Tea with Thick Cheese Foam', 'Matcha with Cheese Foam', 'Scone Set'],
    drinkCategories: ['Brown Sugar Milk Tea', 'Cheese Foam', 'Matcha Series'],
    drinkCategorySlugs: ['brown-sugar-milk-tea', 'cheese-foam', 'matcha-series'],
    priceRange: '$$$',
    halalFriendly: false,
    seatingAvailable: true,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=1200&auto=format&fit=crop',
    featured: true,
    published: true,
  },

  // The Whale Tea
  {
    id: 'outlet-14',
    name: 'The Whale Tea Punggol',
    slug: 'the-whale-tea-punggol',
    brandId: 'brand-10',
    brandName: 'The Whale Tea',
    brandSlug: 'the-whale-tea',
    town: 'Punggol',
    townSlug: 'punggol',
    mall: 'Waterway Point',
    address: '83 Punggol Central, #B1-12, Waterway Point, Singapore 828761',
    nearestMrt: 'Punggol',
    mrtSlug: 'punggol-mrt',
    openingHours: 'Daily 10am–10pm',
    googleMapsUrl: 'https://maps.google.com/?q=Waterway+Point+Punggol+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['Whale Milk Tea', 'Yakult Strawberry', 'Winter Melon Bubble Tea'],
    drinkCategories: ['Classic Milk Tea', 'Yakult Series', 'Fruit Tea'],
    drinkCategorySlugs: ['classic-milk-tea', 'yakult-series', 'fruit-tea'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },

  // Toa Payoh
  {
    id: 'outlet-15',
    name: 'LiHo Tea Toa Payoh',
    slug: 'liho-tea-toa-payoh',
    brandId: 'brand-4',
    brandName: 'LiHo Tea',
    brandSlug: 'liho-tea',
    town: 'Toa Payoh',
    townSlug: 'toa-payoh',
    mall: 'HDB Hub',
    address: '490 Lorong 6 Toa Payoh, #01-12, HDB Hub, Singapore 310490',
    nearestMrt: 'Toa Payoh',
    mrtSlug: 'toa-payoh-mrt',
    openingHours: 'Mon–Sat 9am–9pm · Sun 10am–8pm',
    googleMapsUrl: 'https://maps.google.com/?q=HDB+Hub+Toa+Payoh+Singapore',
    deliveryLinks: [{ platform: 'GrabFood', url: 'https://grab.com' }],
    popularDrinks: ['LiHo Milk Tea', 'Brown Sugar Series', 'Yakult Green Tea'],
    drinkCategories: ['Classic Milk Tea', 'Brown Sugar Milk Tea', 'Yakult Series'],
    drinkCategorySlugs: ['classic-milk-tea', 'brown-sugar-milk-tea', 'yakult-series'],
    priceRange: '$',
    halalFriendly: true,
    seatingAvailable: false,
    image: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
  },
];

// ─────────────────────────────────────────
// Helper: slugify
// ─────────────────────────────────────────
export function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}
